"""Initial migration.

Revision ID: 3506c6a93ea6
Revises: 
Create Date: 2021-08-03 14:49:12.957790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3506c6a93ea6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('timestamp_uninstall', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_blacklisted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('auth_token', sa.String(length=256), nullable=True),
    sa.Column('shop_unique_id', sa.String(length=256), nullable=True),
    sa.Column('shop_url', sa.String(length=256), nullable=True),
    sa.Column('shopify_access_token', sa.String(length=256), nullable=True),
    sa.Column('shopify_recurring_subscription_id', sa.String(length=256), nullable=True),
    sa.Column('onboarding_shopify_added_webhooks', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
